// Generated by dlbBuildBaseApp.py. Do not edit by hand.

const String startupSandboxSubdir = 'BRHC';

class StartupDataFile {
  final String name;
  final String? assetPath;
  final String sandboxName;
  final bool readOnly;
  final bool required;

  const StartupDataFile({
    required this.name,
    required this.assetPath,
    required this.sandboxName,
    required this.readOnly,
    required this.required,
  });
}

const List<StartupDataFile> startupDataFiles = [
  StartupDataFile(
    name: 'brhc.db',
    assetPath: 'assets/databases/brhc.db',
    sandboxName: 'brhc.db',
    readOnly: true,
    required: true,
  ),
  StartupDataFile(
    name: 'brhc_user.db',
    assetPath: 'assets/databases/brhc_user.db',
    sandboxName: 'brhc_user.db',
    readOnly: false,
    required: true,
  ),
];
