// Generated by dlbBuildBaseApp.py. Do not edit by hand.

import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:sqflite/sqflite.dart';

import 'startup_data_files.dart';

Future<Directory> resolveStartupSandboxDirectory() async {
  final supportDir = await getApplicationSupportDirectory();
  final brhcDir = Directory(p.join(supportDir.path, startupSandboxSubdir));
  await brhcDir.create(recursive: true);
  return brhcDir;
}

Future<void> _copyAssetToFile(String assetPath, File destination) async {
  final data = await rootBundle.load(assetPath);
  final bytes = data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
  await destination.writeAsBytes(bytes, flush: true);
}

bool _isDbFile(String path) {
  return path.toLowerCase().endsWith('.db');
}

Future<void> _verifyFileOpen(StartupDataFile file, String path) async {
  final fileRef = File(path);
  final parent = fileRef.parent;
  if (!await parent.exists()) {
    await parent.create(recursive: true);
  }

  if (!await fileRef.exists()) {
    throw Exception('Startup data file missing: ${fileRef.path}');
  }

  final stat = await fileRef.stat();
  if (stat.size == 0) {
    throw Exception('Startup data file is zero bytes: ${fileRef.path}');
  }

  Database? db;
  try {
    db = await openDatabase(fileRef.path);
    await db.rawQuery('SELECT name FROM sqlite_master LIMIT 1');
  } finally {
    await db?.close();
  }
}

Future<void> verifyAndPrepareStartupData() async {
  final files = startupDataFiles;
  if (files.isEmpty) {
    return;
  }
  final brhcDir = await resolveStartupSandboxDirectory();

  final brhcDbEntry = files.firstWhere(
    (entry) => entry.sandboxName == 'brhc.db',
    orElse: () => throw StateError('Missing startup entry for brhc.db'),
  );
  final userDbEntry = files.firstWhere(
    (entry) => entry.sandboxName == 'brhc_user.db',
    orElse: () => throw StateError('Missing startup entry for brhc_user.db'),
  );

  final brhcDbFile = File(p.join(brhcDir.path, 'brhc.db'));
  final userDbFile = File(p.join(brhcDir.path, 'brhc_user.db'));

  if (!await brhcDbFile.exists()) {
    final assetPath = brhcDbEntry.assetPath;
    if (assetPath == null || assetPath.isEmpty) {
      throw StateError('Missing assetPath for brhc.db');
    }
    await _copyAssetToFile(assetPath, brhcDbFile);
  }

  if (!await userDbFile.exists()) {
    final assetPath = userDbEntry.assetPath;
    if (assetPath == null || assetPath.isEmpty) {
      throw StateError('Missing assetPath for brhc_user.db');
    }
    await _copyAssetToFile(assetPath, userDbFile);
  }

  await _verifyFileOpen(brhcDbEntry, brhcDbFile.path);
  await _verifyFileOpen(userDbEntry, userDbFile.path);
}
